config/routes.rb
Tripclub::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope module: :web do
    root to: "welcome#index"

    resources :posts, only: [:index, :show]
    resources :houses, only: [:index, :show] do
      scope module: :houses do
        resources :bookings, only: [:new, :create]
      end
    end
    resources :pages, only: [:show]
    resources :events, only: [:index, :show]
    resources :travel_categories, only: [:show]
    resources :travel_ideas, only: [:show]

    namespace :admin do
      resources :settings,    :only => [:update]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index]
    end
  end

  

end

app/models/menu.rb
# == Schema Information
#
# Table name: menus
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Menu < ActiveRecord::Base
  has_many :items
end

app/models/menu/item.rb
# == Schema Information
#
# Table name: menu_items
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  url        :string(255)
#  menu_id    :integer
#  position   :integer
#  ancestry   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Menu::Item < ActiveRecord::Base
  has_ancestry

  belongs_to :menu

  def to_s
    title
  end
end

app/views/web/shared/menu/_top_menu.html.haml
%ul.nav#top-menu
  %li= link_to 'О нас', page_path(:about)
  %li= link_to 'Контакты', page_path(:contacts)
  %li 
    = link_to 'Идеи для путешествий', '#'
    %ul.sub-menu
      - travel_categories.each do |category|
        %li= link_to category, travel_category_path(category)

  %li= link_to 'Аренда квартир', houses_path
  %li= link_to 'Календарь событий', events_path
  %li= link_to 'Блог', posts_path
  -# - items.each do |item|
  -#   %li
  -#     = link_to item, item.url
  -#     - if item.has_children?
  -#       = render 'web/shared/menu/top_menu_inner', items: item.children

app/views/web/shared/menu/_top_menu_inner.html.haml
%ul.sub-menu
  - items.each do |item|
    %li
      = link_to item, item.url
      - if item.has_children?
        = render 'web/shared/menu/top_menu_inner', items: item.children