config/routes.rb
Tripclub::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope module: :web do
    root to: "welcome#index"

    resources :posts, only: [:index, :show]
    resources :houses, only: [:index, :show] do
      scope module: :houses do
        resources :bookings, only: [:new, :create]
      end
    end
    resources :pages, only: [:show]
    resources :events, only: [:index, :show]
    resources :travel_categories, only: [:show]
    resources :travel_ideas, only: [:show]

    namespace :admin do
      resources :settings,    :only => [:update]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index]
    end
  end

  

end

app/views/layouts/shared/web/_category_header.html.haml
#category-name
  #category-inner
    %h3 "Здесь надо написать какой нибудь слоган, или приветственный текст"
    %p А здесь продолжение шрифтом поменьше :)
/ end .category-name

app/views/layouts/shared/web/_footer.html.haml
#footer
  #footer-content.clearfix
    #footer-widgets.clearfix
      #recent-posts-3.footer-widget.widget_recent_entries
        %h4.widgettitle Идеи для путешествий
        %ul
          - recent_travel_ideas.each do |idea|
            %li= link_to idea, travel_idea_path(idea)

      #recent-posts-3.footer-widget.widget_recent_entries
        %h4.widgettitle Последние посты
        %ul
          - recent_posts.each do |post|
            %li= link_to post, post_path(post)

      #recent-posts-3.footer-widget.widget_recent_entries
        %h4.widgettitle Последние квартиры
        %ul
          - recent_houses.each do |house|
            %li= link_to house, house_path(house)

      #customlogowidget-3.footer-widget.widget_customlogowidget
        %p#footer-logo
        %p Небольшой текст с адресом и телефоном

app/views/layouts/shared/web/_from_blog.html.haml
#from-blog
  #recent-posts-5.main-widget.widget_recent_entries
    %h3.title Блог
    %ul
      - recent_posts.each do |post|
        %li= link_to post, post_path(post)

app/views/layouts/shared/web/_head.html.erb
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Tripclub.su | <%= title %></title>

<link rel="stylesheet" href="/style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/css/colorpicker.css" type="text/css" media="screen" />

<link href='http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Kreon:light,regular' rel='stylesheet' type='text/css'/>

<!--[if lt IE 7]>
	<link rel="stylesheet" type="text/css" href="/css/ie6style.css" />
	<script type="text/javascript" src="/js/DD_belatedPNG_0.0.8a-min.js"></script>
	<script type="text/javascript">DD_belatedPNG.fix('img#logo, span.overlay, a.zoom-icon, a.more-icon, #menu, #menu-right, #menu-content, ul#top-menu ul, #menu-bar, .footer-widget ul li, span.post-overlay, #content-area, .avatar-overlay, .comment-arrow, .testimonials-item-bottom, #quote, #bottom-shadow, #quote .container');</script>
<![endif]-->
<!--[if IE 7]>
	<link rel="stylesheet" type="text/css" href="/css/ie7style.css" />
<![endif]-->
<!--[if IE 8]>
	<link rel="stylesheet" type="text/css" href="/css/ie8style.css" />
<![endif]-->

<script type="text/javascript">
	document.documentElement.className = 'js';
</script>

<link rel='stylesheet' id='et_responsive-css'  href='/css/responsive.css?ver=3.7' type='text/css' media='all' />
<link rel='stylesheet' href='/css/jquery.fancybox-1.3.4.css' type='text/css' media='all' />

<!-- used in scripts -->
<style type="text/css">
  body { background-color: #6a8e94; }
</style>
<link id='droid_sans' href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css' />
<style type='text/css'>
  body { font-family: 'Droid Sans', Arial, sans-serif !important;  }
</style>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<style type="text/css">
  .recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}
</style>
<style type="text/css">
  #et_pt_portfolio_gallery { margin-left: -41px; margin-right: -51px; }
  .et_pt_portfolio_item { margin-left: 35px; }
  .et_portfolio_small { margin-left: -40px !important; }
  .et_portfolio_small .et_pt_portfolio_item { margin-left: 32px !important; }
  .et_portfolio_large { margin-left: -26px !important; }
  .et_portfolio_large .et_pt_portfolio_item { margin-left: 11px !important; }
</style>

<%= stylesheet_link_tag "web/application", :media => "all" %>
</head>

app/views/layouts/shared/web/_header.html.haml
#header.clearfix
  %a{href: "/"}
    %img#logo{alt: "TripClub.su", src: asset_path('logo-big2.png') }/
  %a#mobile_nav.closed{href: "#"}
    Меню
    %span
  = render_menu slug: 'top_menu', tpl: 'web/shared/menu/top_menu'
  #additional-info
    #et-social-icons
      %a{href: "#", target: "_blank"}
        %img{alt: "Twitter", src: "/images/twitter.png"}/
      %a{href: "#", target: "_blank"}
        %img{alt: "Facebook", src: "/images/facebook.png"}/

app/views/layouts/shared/web/_multimedia_bar.html.haml
#multi-media-bar
  %h3.title Multi Media Bar
  #et-multi-media.clearfix
    %a#left-multi-media{href: "#"} Previous
    %a#right-multi-media{href: "#", next: ""}
    #media-slides
      .media-slide
        .thumb
          %a.fancybox{href: "http://elegantthemes.com/preview/DeepFocus/wp-content/uploads/2010/09/2.jpg", rel: "media", title: "Make A Wish"}
            %img.multi-media-image{alt: "Make A Wish", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/2-120627_48x48.jpg", width: "48"}/
            %span.more
          .media-description
            %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis porta nibh, a...
            %span.media-arrow
        / end .thumb
        .thumb
          %a.fancybox{href: "http://elegantthemes.com/preview/DeepFocus/wp-content/uploads/2010/09/3.jpg", rel: "media", title: "The Morning Dew"}
            %img.multi-media-image{alt: "The Morning Dew", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/3-135379_48x48.jpg", width: "48"}/
            %span.more
          .media-description
            %p Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;...
            %span.media-arrow
        / end .thumb
        .thumb
          %a.et-video.fancybox{href: "#et_video_post_270", title: "Purple Haze"}
            %img.multi-media-image{alt: "Purple Haze", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/s-1-624464_48x48.png", width: "48"}/
            %span.more
          .media-description
            %p Nullam at massa orci. Nulla suscipit adipiscing tincidunt. Donec purus arcu, posuere et...
            %span.media-arrow
        / end .thumb
        .thumb
          %a.fancybox{href: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/2010/09/s-3.png", rel: "media", title: "Bridge To Nowhere"}
            %img.multi-media-image{alt: "Bridge To Nowhere", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/s-3-630122_48x48.png", width: "48"}/
            %span.more
          .media-description
            %p Donec sed metus ipsum, laoreet suscipit purus. Fusce ante lorem, luctus et tincidunt...
            %span.media-arrow
        / end .thumb
        .thumb
          %a.fancybox{href: "http://www.elegantthemes.com/preview/DeepFocus/wp-content/uploads/2010/09/6.jpg", rel: "media", title: "The Lonely Ladybug"}
            %img.multi-media-image{alt: "The Lonely Ladybug", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/6-82087_48x48.jpg", width: "48"}/
            %span.more
          .media-description
            %p Nullam at massa orci. Nulla suscipit adipiscing tincidunt. Donec purus arcu, posuere et...
            %span.media-arrow
        / end .thumb
        .thumb
          %a.et-video.fancybox{href: "#et_video_post_259", title: "Monkeys Take a Bath"}
            %img.multi-media-image{alt: "Monkeys Take a Bath", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/7-78254_48x48.jpg", width: "48"}/
            %span.more
          .media-description
            %p Vivamus sit amet quam lacus, et suscipit massa. Morbi eget ligula vitae massa...
            %span.media-arrow
        / end .thumb
        .thumb.last
          %a.fancybox{href: "http://elegantthemes.com/preview/DeepFocus/wp-content/uploads/2010/09/8.jpg", rel: "media", title: "Birds of Beauty"}
            %img.multi-media-image{alt: "Birds of Beauty", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/8-70372_48x48.jpg", width: "48"}/
            %span.more
          .media-description
            %p Sed sed tellus ac turpis mollis euismod. Ut eget justo non felis sollicitudin suscipit....
            %span.media-arrow
        / end .thumb
      / end .media-slide
      .media-slide
        .thumb
          %a.fancybox{href: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/2010/09/s-2.png", rel: "media", title: "Summer Wheat"}
            %img.multi-media-image{alt: "Summer Wheat", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/s-2-458164_48x48.png", width: "48"}/
            %span.more
          .media-description
            %p Donec sed metus ipsum, laoreet suscipit purus. Fusce ante lorem, luctus et tincidunt...
            %span.media-arrow
        / end .thumb
        .thumb
          %a.et-video.fancybox{href: "#et_video_post_253", title: "Calm Before The Storm"}
            %img.multi-media-image{alt: "Calm Before The Storm", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/shutterstock_5055934-183251_48x48.jpg", width: "48"}/
            %span.more
          .media-description
            %p Donec auctor ullamcorper nunc, vitae pellentesque mi fringilla posuere. Maecenas semper...
            %span.media-arrow
        / end .thumb
        .thumb
          %a.fancybox{href: "http://elegantthemes.com/preview/DeepFocus/wp-content/uploads/2010/09/shutterstock_20951311.jpg", rel: "media", title: "Bamboo Shoots"}
            %img.multi-media-image{alt: "Bamboo Shoots", height: "48", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/shutterstock_20951311-105492_48x48.jpg", width: "48"}/
            %span.more
          .media-description
            %p Etiam cursus, nibh in suscipit tincidunt, ante enim scelerisque lacus, sed consectetur...
            %span.media-arrow

app/views/layouts/shared/web/_page_header.html.haml
#category-name
  #category-inner
    %h1#category-title= title

app/views/layouts/shared/web/_scripts.html.erb
<%= javascript_include_tag 'web/application' %>

<script type='text/javascript' src='http://code.jquery.com/jquery-migrate-1.2.1.min.js'></script>
<script type='text/javascript' src='/js/jquery.cycle.all.min.js?ver=1.0'></script>
<script src="/js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="/js/jquery.fancybox.1.3.4.pack.js" type="text/javascript"></script>
<script src="/js/superfish.js" type="text/javascript"></script>
<script src="/js/custom.js" type="text/javascript"></script>
<script type="text/javascript"> 
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script> 
<script type="text/javascript"> 
  var pageTracker = _gat._getTracker("UA-5205247-2");
  pageTracker._trackPageview();
</script> 

<script type='text/javascript' src='/js/jquery.flexslider-min.js?ver=1.0'></script>
<script type='text/javascript' src='/js/et_flexslider.js?ver=1.0'></script>
<script type='text/javascript' src='/js/jquery.cookie.js?ver=1.0'></script>
<script type='text/javascript'>
  /* <![CDATA[ */
var et_ptemplates_strings = {"captcha":"Captcha","fill":"Fill","field":"field","invalid":"Invalid email"};
/* ]]> */
</script>

app/views/layouts/shared/web/_services.html.haml
#services.clearfix
  .service
    %h3.title Услуга №1
    .thumb
      %a{href: "http://www.elegantthemes.com/preview/Chameleon/about/"}
        %img.item-image{alt: "Mission Statement", height: "160", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/2010/09/t-1.png", width: "376"}/
        %span.more-icon
    %p Небольшой текст с описанием услуги

  .service
    %h3.title Услуга №2
    .thumb
      %a{href: "http://www.elegantthemes.com/preview/Chameleon/what-i-do/"}
        %img.item-image{alt: "Who We Are", height: "160", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/2010/09/t-2.png", width: "376"}/
        %span.more-icon
    %p Небольшой текст с описанием услуги

  .service.last
    %h3.title Услуга №3
    .thumb
      %a{href: "http://www.elegantthemes.com/preview/Chameleon/who-i-am/"}
        %img.item-image{alt: "What We Do", height: "160", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/2010/09/t-3.png", width: "376"}/
        %span.more-icon
    %p Небольшой текст с описанием услуги

app/views/layouts/shared/web/_slider.html.haml
.flex-container
  #featured.flexslider
    %ul.slides
      %li.slide
        %img{alt: "Purple Haze", height: "332", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/2010/09/s-1.png", width: "960"}/
        .featured-top-shadow
        .featured-bottom-shadow
        .featured-description
          %h2.featured-title
            %a{href: "http://www.elegantthemes.com/preview/Chameleon/2010/09/15/purple-haze/"} Purple Haze
          %p Nullam at massa orci. Nulla suscipit adipiscing tincidunt. Donec purus arcu, posuere et pellentesque vitae, mattis in dui. Ut quis mi in erat blandit porta a sed risus. Maecenas nibh nisl, blandit in vestibulum non, pharetra id erat. Aenean vulputate elementum velit. Sed sed...
          %a.readmore{href: "http://www.elegantthemes.com/preview/Chameleon/2010/09/15/purple-haze/"} Read More

      %li.slide
        %img{alt: "Bridge To Nowhere", height: "332", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/2010/09/s-3.png", width: "960"}/
        .featured-top-shadow
        .featured-bottom-shadow
        .featured-description
          %h2.featured-title
            %a{href: "http://www.elegantthemes.com/preview/Chameleon/2010/09/15/bridge-to-nowhere/"} Bridge To Nowhere
          %p Donec sed metus ipsum, laoreet suscipit purus. Fusce ante lorem, luctus et tincidunt vel, vestibulum et mauris. Sed ut diam est. Nulla eget elit dui, vitae auctor nibh. Sed non leo a tellus condimentum posuere ut quis leo. Suspendisse accumsan ullamcorper nunc. Sed nulla odio,...
          %a.readmore{href: "http://www.elegantthemes.com/preview/Chameleon/2010/09/15/bridge-to-nowhere/"} Read More

      %li.slide
        %img{alt: "Summer Wheat", height: "332", src: "http://cdn.elegantthemes.com/preview/Chameleon/wp-content/uploads/et_temp/feat-3-664858_960x332.png", width: "960"}/
        .featured-top-shadow
        .featured-bottom-shadow
        .featured-description
          %h2.featured-title
            %a{href: "http://www.elegantthemes.com/preview/Chameleon/2010/09/15/summer-wheat/"} Summer Wheat
          %p Donec sed metus ipsum, laoreet suscipit purus. Fusce ante lorem, luctus et tincidunt vel, vestibulum et mauris. Sed ut diam est. Nulla eget elit dui, vitae auctor nibh. Sed non leo a tellus condimentum posuere ut quis leo. Suspendisse accumsan ullamcorper nunc. Sed nulla odio,...
          %a.readmore{href: "http://www.elegantthemes.com/preview/Chameleon/2010/09/15/summer-wheat/"} Read More

#controllers